### ISSUE TITLE
Pi Presents Gapless Running Lobby Display

### ISSUE THREAD

**Issue by John37m** [KenT2/pipresents-gapless#10]
KenT2,

Thank you very much for writing Pi Presents. When I talked to you a few months ago I told you about a physics demonstration we were putting in our hands on science museum located in our University of Florida Physics Department lobby. Well the display is now active and has be running 24/7 for about 1 month now. I told you I would send you a link to the demo.....it's called the "Pendulum Wave Machine" and you can find it on this webpage...

http://www.phys.ufl.edu/department/exhibits.shtml

It runs Pi Presents Gapless version 1.3 on a Raspberry Pi 2 board. The show has a main slide show that runs nonstop until a guest presses the start button. Starting triggers a sub-show slide show that also controls the state of the machine so it stays in sync with the show. We use three GPIO pins for switches....one to start the machine by viewers and trigger the sub-show off of the main show, and two micro switches that tell us the position of the machine (it's state). We also use one GPIO pin for driving the electrical motor that operates the machine.

If you go to the webpage listed above you will find 4 links beside the pendulum wave, two are videos, one is the unveiling party and one shows the slides of the show that runs on the machine.

Thank You very much for creating Pi Presents!! 
John M
Physics Department, University of Florida

**Comment by KenT2** [comment]
Thanks John. I've added this to the Wordpress blog.
