### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by straymoose** [KenT2/pipresents-gapless#105]
I installed Pi Presents on a test last year... Finally doing it again... Fresh Pi setup ready... 

Following the readme (I am very much a dabbler with little clue to anything complicated but can follow instructions generally!) tried to install all the required packages and only python-imaging now python-pil will install just says the rest are not found... I'm sure I'm doing something daft so please take mercy on me and help if you can!!!

**Comment by KenT2** [comment]
I have a  feeling python imaging is already installed in the image so it sounds like a download problem. I know installation works for many so some suggestions

do sudo apt-get update first
Not connected to the internet
Something temporarily wrong with the Raspbian repository
Not using Raspbian Stretch
