### ISSUE TITLE
liveshow swipe through images touchscreen

### ISSUE THREAD

**Issue by natanja** [KenT2/pipresents-gapless#108]
Hi!!
Is it possible to have a liveshow where you can add images to a specific map and not have to worry any further. And once the show is started you can go thorugh the images with swipes to the left or right? So I have a touchscreen and I have a pi with pipresents. Would this be possible?

**Comment by KenT2** [comment]
Yes, add the images to a specific directory. No swiping, but you can add buttons (click areas) to the screen to move forward and backward. I think adding a new image will start the show from the beginning again though.
Look at pp_clickarea_1p3 example.
