### ISSUE TITLE
/pipresents/unit1/core/monitor on

### ISSUE THREAD

**Issue by RogierQ** [KenT2/pipresents-gapless#109]
When i try to get the monitor from standby with the command below nothing happends
/pipresents/unit1/core/monitor on

but when i reboot the pi the monitor goed on :-(

any solution to this?

**Comment by KenT2** [comment]
Some ideas
Are you using the -b command line option to disable screen blanking.
Try the cec command instead. I vaguely remember having the same problem with the monitor command.
Do check it works when sent locally in case there is a bug in the OSC function of PP

**Comment by RogierQ** [comment]
thanks!
were can i find the cec commands?

**Comment by KenT2** [comment]
in the manual next to the monitor command
