### ISSUE TITLE
Radiobuttonshow music cuts midway after 1 boot

### ISSUE THREAD

**Issue by pholdahl** [KenT2/pipresents-gapless#111]
Greetings Ken!

I have a strange issue that irregularly occurs. When it happens, my raspberry pi has been off for hours, or even days. I have my radiobuttonshow on autostart on boot , following your pp manual guidelines on how to do this. But when I boot the pi for the first time, after it not being on for a couple of hours, or days. The first show of my radiobuttonshow, the music cuts half way, silence, and buttons or keypresses are unresponsive. Except for ctrl, alt, break. When I reboot after this first failed autostart, everything works fine.

I have the same show set up on 2 of my raspberry pi 3B+, both experiencing the same problem.

The start show of my radiobuttonshow consists of a track with a 2 minute long .mp3 file showing a black background colour, its on infinite loop, and the second track is a 3 second silent .mp3 with showcontrols set to openexclusive a different show.

I´ve been searching the web on and of for weeks now, but I have not found anyone else experiencing the same problem.

Any ideas on what could be the reason?

**Comment by KenT2** [comment]
Hi
This one has stumped me. I cannot think of a set of circumstances that could cause this.
Screen blanking should not cause sound to stop. But just to be sure are you using the -b command line option to disable it.
Possibly a dodgy audio track, try another track. Does the track stop in the middle of the track or at the beginning or end.
If CTRL-BREAk stops PP then PP is still running. Take a look at the debug log by running  Pi Presents with the -d command line option and looking at the file /pipresents/pp_logs/pp_log.txt. Post it here if you want.
