### ISSUE TITLE
Number Pad to trigger tracks

### ISSUE THREAD

**Issue by Alchemist45** [KenT2/pipresents-gapless#112]
A quick question, I hope.
Can you tell how or point me in the right direction on this issue?
I want to trigger running tracks using a usb key/number pad.  How can I get a specific show to run with keypad 1 and a different one with keypad 2?

Probably simple?  

Thanks for any help you can give!

Scott (Alchemist45)

**Comment by KenT2** [comment]
If its a numeric keypad on a keyboard then the keys are KP_0 KP_1, KP_Enter etc. Codes may depend on if numlock  key is set.

If its a standalone keypad then you may need to use the pp_inputdevicedriver.py There are some  instructions in the manual as well as in the .py file
Also the program input_device.py will help you with the configuration file.

KP_Space                         65408     0xff80
KP_Tab                           65417     0xff89
KP_Enter                         65421     0xff8d
KP_F1                            65425     0xff91
KP_F2                            65426     0xff92
KP_F3                            65427     0xff93
KP_F4                            65428     0xff94
KP_Multiply                      65450     0xffaa
KP_Add                           65451     0xffab
KP_Separator                     65452     0xffac
KP_Subtract                      65453     0xffad
KP_Decimal                       65454     0xffae
KP_Divide                        65455     0xffaf
KP_0                             65456     0xffb0
KP_1                             65457     0xffb1
KP_2                             65458     0xffb2
KP_3                             65459     0xffb3
KP_4                             65460     0xffb4
KP_5                             65461     0xffb5
KP_6                             65462     0xffb6
KP_7                             65463     0xffb7
KP_8                             65464     0xffb8
KP_9                             65465     0xffb9
KP_Equal
