### ISSUE TITLE
Autostart Pi Presents instructions not working

### ISSUE THREAD

**Issue by mercuryrsng** [KenT2/pipresents-gapless#115]
Hello,

I am a new Raspberry Pi/Linux user and I am trying to use the instructions in your guide on how to autostart Pi Presents.  I am currently running Raspbian Buster.
In the instructions, it states that the autostart file is located:
/home/pi/.config/lxsession/LXDE-pi/autostart

The problem is the lxsession folder does not exist.  I have to imagine that in later versions, they have changed the location of the autostart file.

Where can I find it now?  Or, how can I get my profile to start up on boot?
Please go easy on me as I am still learning bash :-).

Love the product!

**Comment by mercuryrsng** [comment]
NEVERMIND all I had to do was slow down and read.....Thanks

However, my only issue now is how do I autostart the pp_manager.py file so that I can edit the shows in a browser?  Prior to changing this autostart file, I had edited the rc.local file and it was working....but now it isn't and I have to manually start the program.

**Comment by KenT2** [comment]
autostarting pp_manager.py uses the same technique as starting PP

**Comment by mercuryrsng** [comment]
I figured it out. Thanks again!
