### ISSUE TITLE
ImageTK

### ISSUE THREAD

**Issue by pramodmadhav** [KenT2/pipresents-gapless#117]
after running pipresents.py i get following error 
ImportError : cannot import name imagetk
I am using raspberry pi 4 with raspbian buster

**Comment by KenT2** [comment]
Sounds like you have missed out an installation step:
     sudo apt-get install python-imaging-tk

**Comment by pramodmadhav** [comment]
Ok let me do the installation process once again and will let you know.
But as far as my knowledge I have done that
Is it something to do with is (buster)?

**Comment by pramodmadhav** [comment]
Problem solved
Instead of python-imaging-tk I had to type
Python-pil.imagtk
May be because I installed python-pil instead of python-imaging which was prompted at the time of installation
Is it ok or not I don't know

**Comment by pramodmadhav** [comment]
now the error window comes with profile not specified as explained in installation procedure.
now when try to down load the examples with"         wget https://github.com/KenT2/pipresents-gapless-examples/tarball/master -O - | tar xz"
I get following error message
HTTP request sent awaiting response  404 not found
what could be the reason?

**Comment by KenT2** [comment]
I'm not sure about the python-pil bit, I just let it do what it wants. If PP works its probably OK!

Are you doing the wget fron the PI's terminal. I get 404 from the browser on my PC

Maybe though '404 not found' indicates github or your internet connection is down, just try again.
If all else fails just point your browser and the github repo and use the Clone and Downlod>Download ZIP buttons

**Comment by pramodmadhav** [comment]
I could down load the examples and was able to see the examples.
Also read your manual.I saw ocs in that. 
can PiPresents sync multiple videos on multiple raspberries?may be using OSC

**Comment by KenT2** [comment]
Yes OSC will do it however it depends on the accuracy of the sync you require. There will a delay of a second, probably less. You might be able to use the video playout to improve it.

For 2 videos you might be able to  use a PI4 with 2 monitors, arrange them one on top of the other using the screen configuration utility.

Something like Pi-Wall will do a frame sync IIRC

**Comment by pramodmadhav** [comment]
thanks,
I came accross follwing link to sync the videos on multiple rpis,
it works well for me on 9 nos of rpi without any problem
if I want to integarte that in pi presents can you tell me how to do it.
https://github.com/turingmachine/omxplayer-sync

**Comment by KenT2** [comment]
Looks an interesting package. 
omxdriver is called in pp_omxdriver.py. It then uses dbus to pause the video and to monitor the position of the video to freeze it at the end; both part of achieveing gapless operation.

It might be better to replace the whole of pp_omxdriver.py with software based on omxplayer-sync ideas.

**Comment by pramodmadhav** [comment]
What about pp-omxdriver.pyc?.
frankly speaking I do not know all these things.
Only if you could add this as package or additional feature to pi presents that will be very useful.

**Comment by KenT2** [comment]
Transferred to Beep
