### ISSUE TITLE
Tracks don't loop and progress before button is pressed

### ISSUE THREAD

**Issue by jessekirbs** [KenT2/pipresents-gapless#118]
Hey Ken - Thanks for your amazing software. I'm running into a small issue. I'd like to have a mediashow that plays two tracks. I'd like these tracks to loop infinitely until a button (soldered to the Pi) is pressed, which should cycle to the next track. The button works perfectly and cycles between the two tracks, however the individual tracks do not loop and move to the next track upon reaching their end. I've attached two images of the show and track options. Please let me know if I am doing something incorrectly and how to fix this issue. Thank you!

![IMG_5615](https://user-images.githubusercontent.com/8700046/66264549-48a2af80-e7bc-11e9-89be-488dc8ea1b4f.JPG)
![IMG_5616](https://user-images.githubusercontent.com/8700046/66264550-493b4600-e7bc-11e9-9ae9-dc57fc6c990a.JPG)

**Comment by KenT2** [comment]
For each individual video track there is an option to loop the track, its not in the track defaults in the Show. I think this should do what you want, if not use subshows. Put each track in a repeating mediashow and the two mediashows in a not repeating  top level mediashow
