### ISSUE TITLE
Presentation Sequence Gap

### ISSUE THREAD

**Issue by nt49949390** [KenT2/pipresents-gapless#119]
Hello Ken,

First of all, I would like to thank you for PiPresents. I have a question about a simple presentation for children I am going to make. 
The idea is about a video player which has two buttons. The first is a “next” button, playing video files one after another. The other button starts playing from the first video of the sequence, something like “safe” button, in case someone wants to start from the beginning.
I did it with mediashow successfully but there’s a gap approx one second which is not acceptable by the organizers. 
So, I tried with the artmediashow which was gapless and it worked fine. I did a “next” gpio button which also worked well. But the problem is that I can’t make a gpio button to start  playing from the first track in the artmediashow. Could please help?

Kind regards 

Nikos

**Comment by KenT2** [comment]
I think to make the artmedishow a subshow of a mediashow which has the artmediashow as its single track. Then the stop or exit commands in the artmediashow will exit it to the mediashow and restart the artmediashow
