### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dhunink** [KenT2/pipresents-gapless#12]
Hi,

to be honest: until today I never knew about the existence of Pi Presents. That's a shame: I believe this is such un incredible piece of code that it's art in itself. I'm so impressed and are already seeing so many possible ways to use this! Compliments for that!

One thing that I couldn't find in the docs (but maybe I just missed it) is the possibility to fast forward or rewind video.
Consider the following scenario:
- a single video is playing and looping
- when button A is pressed, the video is playing twice as fast
- when button B is pressed, the video is playing four times as fast
- when button C is pressed, the video is rewinding at double speed
- when button D is pressed, the video is rewinding at four times the normal playback speed
- when button E is pressed, the video is paused

Would that be a scenario that's possible to achieve using Pi Presents? 

(off course, if this is possible and I am deciding to incorporate it into the project I'm working on for the next couple of days, I will make a small donation, since the project isn't totally non-profit, although I'm not really making money out of it. But I'm so impressed by this project that I'd be happy to provide a little financial contribution).

**Comment by KenT2** [comment]
PP just plays videos by starting omxplayer so is limited to  what omxplayer can do.You need to use run time commands e.g. omx-2  See here for list of commands https://github.com/popcornmix/omxplayer

Not sure how well omxplayer works in this area. Try omxplayer from the command line first.

Ken
