### ISSUE TITLE
Parallax PIR Sensor Problem

### ISSUE THREAD

**Issue by ghost** [KenT2/pipresents-gapless#122]
I am having a lot of trouble with pi presents and getting it to work with a pir sensor. My goal is to use it to cycle through a series of animations with the trigger for the cycle being motion detection from a pir sensor. The only problem is that I cant get the sensor to work within pipresents. I am very new to rasberry pi/ coding/ anything of this sort so I was hoping someone could help me. I have the sensor working within python, it tells me when it senses motion and senses no motion (video below) and then I have it set up in pi presents (on pin 22) with the default pir sensor show (pp_exhibit_1p3) but still nothing is happening. Im just lost I guess. Would appreciate any help. All of my documentation is included in the google drive folder below.

https://drive.google.com/drive/folders/1cc_otpzz8awTVPdKn0OhFmwGJphDGHH0?usp=sharing

**Comment by KenT2** [comment]
pp_exhibit1p3 uses pin P1-11 for the PIR, have you changed gpio.cfg.
Are you confusing physical pin numbers and GPIO numbers. p1-11 is a physical number
