### ISSUE TITLE
ImageTK

### ISSUE THREAD

**Issue by s-m-arty** [KenT2/pipresents-gapless#127]
after running pipresents.py i get following error
ImportError : cannot import name imagetk

**Comment by KenT2** [comment]
you have missed out during installation

     sudo apt-get install python-imaging-tk

**Comment by s-m-arty** [comment]
I have not forgotten this step. However, the following message appears in this step
`Fehl:1 http://raspbian.raspberrypi.org/raspbian buster/main armhf python-pil.imagetk armhf 5.4.1-2
  404  Not Found [IP: 93.93.128.193 80]
E: Fehlschlag beim Holen von http://raspbian.raspberrypi.org/raspbian/pool/main/p/pillow/python-pil.imagetk_5.4.1-2_armhf.deb 404  Not Found [IP: 93.93.128.193 80]`

**Comment by KenT2** [comment]
I installed this a couple fo days ago so I know it works, however it does not now so I suspect an intermittent problem with the server. Someone else reported this many months ago, try again later

**Comment by s-m-arty** [comment]
after a new installation it works
