### ISSUE TITLE
Animatronics

### ISSUE THREAD

**Issue by hannapropman** [KenT2/pipresents-gapless#132]
Hello Ken! I am using python script and raspberry pi to control animatronics with some success. My question here is, can i run my scripts through pipresents as readily as media, integral on one paspberry pi. This would solve many problems, and of coarse create new ones i am sure! I have read through all of the types of shows that pipresents can generate, animatronics are mentioned but not to the extent that I would  know I am heading in the right direction. I have a feeling i might be slightly outside of the box on this one, Thank you!

**Comment by KenT2** [comment]
I think you should write your own I/O plugin to do your animatronics, you can define commands with parameters which you include in animation commands in tracks. Make sure the code does not block for more than a few tens of milliseconds by using threads or Tkinter's After command.
