### ISSUE TITLE
documentation: how to make videos fullscreen

### ISSUE THREAD

**Issue by knarrff** [KenT2/pipresents-gapless#14]
Despite pipresents having a GUI for configuration (which makes a lot of sense), I had to resort to the source code to find out how to make omxplayer play videos in fullscreen.

First, let me explain how I do read the code right now: omxplayer would play videos in full screen by default, but pipresents gets the original size of the video and, if no other size is specified by the user, sets that as size for playback. This is not what I expected, and what I would choose as default, but may that be as it is. I didn't find a 'fullscreen' option in the GUI, but there is a 'video window' option. I had to dig into the source code to find that, if I enter just 'warp' there, pipresents will use it's own canvas size as video playback size, which in my case happens to be the full screen, what I want.

This ticket is about making videos play full-screen a little more obvious, and I see multiple choices.

One would be to document this some place. I couldn't find this mentioned anywhere, but the source code. Inside the GUI would make sense. Less optimal, but still ok, would be a tutorial that starts small: how to create a slide show just from pictures and/or videos.

Another option would be to offer a full screen option (radio button or such) directly in the GUI. I would like that best, but one would need to handle the case of this checked _and_ a string in the window options.

In addition, an option to play all videos by default full-screen would be awesome, as otherwise, for a video-slideshow one would need to manually check full-screen for each entry.

I would be willing to help, even coding, but I don't want to maintain this change. Thus: I'd like feedback from the author first as to which direction this should go.

**Comment by KenT2** [comment]
Do you think the manual (manual.pdf in the download) section 5.4.5 needs clarifying.

I could introduce a fullscreen option into the track and show edit menus which would just duplicate 'warp'.
