### ISSUE TITLE
pp_manager functionality

### ISSUE THREAD

**Issue by scotthardwick** [KenT2/pipresents-gapless#24]
I am not really a python coder, but have been trying to read through the manager code.  Am I correct that it isn't using the OSC interface but instead is just able to tell running status by looking at the process list?

I was trying to see if there was a way from the web manager to see which track was in action and was going to try and add some buttons to trigger a show, move to next track, mute/unmute.  

So I guess this has become more of a feature request post :-)

Thanks for considering these items Ken.

Scott

**Comment by KenT2** [comment]
Hi
This would  be possible from pp_manager.py but you would need to get stdin to pipe key presses to Tkinter. 

Better to use the OSC interface of Pi Presents. This allows you to send an 'event' containing a symbolic name which can be associated with play, stop, etc. I think it would be easy to modify pp_oscremote.py to add more buttons.
