### ISSUE TITLE
Toggle GPIO Output

### ISSUE THREAD

**Issue by chuchaki** [KenT2/pipresents-gapless#35]
Hey! Its me again ;-) I have another ( and hopefully the last) question. 

Is it possible to toggle a GPIO output using an GPIO input? 

As an example: I have a button with an integrated LED. When I press it, the system is enabled & the LED goes off. If i press it again, the system is disabled and the LED goes on.

**Comment by KenT2** [comment]
no, but I think its fairly simple to add. I aim to put it in v1.3.2a which I am working on now and is likely to be a month or so away.

**Comment by chuchaki** [comment]
Sounds great, thanks

**Comment by KenT2** [comment]
Now in version 1.3.2a
