### ISSUE TITLE
Shuffle

### ISSUE THREAD

**Issue by chuchaki** [KenT2/pipresents-gapless#36]
Hey, 
I have another Question. If I use Shuffle to play a set of Files, it happens, that files are played again before all others were played. Is this desired? I would think, that this only coud happen if I combine shuffle & repeat.

Thanks and Greetings!

**Comment by KenT2** [comment]
Shuffle just uses a random number generator to select the next track, it does not keep a record of which tracks are played so you can get duplicates. I now realize what shuffle really means.

**Comment by chuchaki** [comment]
Is it possible to include a shuffle in the next release?

**Comment by KenT2** [comment]
Its coded so it will be there. Still a few weeks until release though

**Comment by chuchaki** [comment]
Great!
