### ISSUE TITLE
Problem with a gpio.cfg file

### ISSUE THREAD

**Issue by GeorgeDolan** [KenT2/pipresents-gapless#38]
When I tried to use the appended gpio.cfg file (gpio.txt) I pulled the appended information in the execution_file.txt

I can't pick out what might be wrong in the gpio.cfg file, and don't understand the "traceback" information.

[gpio.txt](https://github.com/KenT2/pipresents-gapless/files/839029/gpio.txt)
[execution_file.txt](https://github.com/KenT2/pipresents-gapless/files/839020/execution_file.txt)
[FailureNotice.txt](https://github.com/KenT2/pipresents-gapless/files/839021/FailureNotice.txt)

I am stuck at this point.    -- George

**Comment by KenT2** [comment]
You have to provide a value for threshold. All my examples use 2 and I've not had problems with this number.
