### ISSUE TITLE
Interactive

### ISSUE THREAD

**Issue by hamelsveld** [KenT2/pipresents-gapless#39]
Hi,

Are there plans to make pipresents interactive.. so playing a signing playlist when inactive but by touching the screen it opens a browser in kiosk mode to a predefined URL?

Like to hear your thoughts. ...

**Comment by KenT2** [comment]
Its already there, see pp_interactive_1p3 for child show and pp_clickareas_1p3 for touch screen.Opening the browser willbe a bit slow though
