### ISSUE TITLE
Menushow always returns with its selected item as the first

### ISSUE THREAD

**Issue by AbsoluteDestiny** [KenT2/pipresents-gapless#4]
This makes it difficult for a user to recall the last item they started.

Ideally it would remember the last selection they made.

**Comment by KenT2** [comment]
Looks like a good idea, think I would implement it as a profile controlled option. I will put it on the to do list.

**Comment by KenT2** [comment]
In version 1.3.2a
I have made it possible to revert and to return to the first track by editing  pp_menushow.py around line 58
self.return_to_zero = True
