### ISSUE TITLE
Support for multiple fonts within one text block

### ISSUE THREAD

**Issue by mortomanos** [KenT2/pipresents-gapless#40]
Is there the possibility to add support for different fonts within the same text block? This would make the creation of ppt-like slides using photos and text much easier. I did a workaround for this, but it seems to be very ineffective.

**Comment by KenT2** [comment]
It looks diffficult to do as it would be necessary to write an editor for a Tkniter text box.

I prepare the slides using powerpoint and use the powerpoint save as jpeg facility

**Comment by mortomanos** [comment]
I think it is not necessary to especially prepare an editor, if one could do some inline tagging, maybe markdown style for different font sizes or similar.
Save as jpg/png is the thing I want to avoid, since I have a lot of "slides" that need to only change text, so it would be necessary to have a workflow for always change text and save as png. For example a "welcome" slide (Foobar Inc. welcomes the following guests: Bugs Bunny, Duffy Duck, ..." that changes the people to welcome on each visit.

**Comment by KenT2** [comment]
A cutdown version markdown or similar would be nice but will require a parser to convert the markdown to commands for the Tkinter Text widget. I cannot find such a thing on the web.

PP already supports the display of web pages so you could use web tracks and html

**Comment by mortomanos** [comment]
What could work is the way via HTML, see this stackoverflow thread: http://stackoverflow.com/questions/35733300/how-to-show-markdown-format-text-in-tkinter
I will look into the displaying of web pages.

**Comment by KenT2** [comment]
Good find, I did see the stackoverflow article but didn't follow the links well enough. I will put this on my to do list but it will not happen for many months.

If you have Python expertise you could create a PiPresents Track Plugin which will create a text widget and populate it Tkniter text widget commands created by parsing the html. The krt_time.py shows how to create the text widget. You can use track_params[] and show_params[] to access the profile data.

**Comment by mortomanos** [comment]
I do have a little bit of Python expertise. Let's see if there is enough time to have a look, but I cannot promise anything at the moment since time is very limited at the moment.
By the way, pipresents is a very cool solution and fits perfectly my needs. I hope that it will be maintained and further developed.

**Comment by mortomanos** [comment]
What could be possible is using the Tkhtml widget and directly display html, that would allow enough formatting options. But I don't know how to place a widget within pipresents, I only saw the create_text methods from Canvas widget, and this is not able to do different formatting.

**Comment by KenT2** [comment]
Tkhtml is a good find. 

You should be able to place any type of widget on a canvas.

You can do this in PP with minimal coding by using a track plugin e.g. krt_time.py. In the draw() function just replace the text widget with a tkhtml widget

**Comment by KenT2** [comment]
This is now built into  Version 1.4.3a. [pipresents-beep]  This is the first version using python3
