### ISSUE TITLE
Make show full screen

### ISSUE THREAD

**Issue by Peter-Brown-1** [KenT2/pipresents-gapless#46]
Hi Ken,
I'm sure that this is just me being stupid but how do I make my Multi Window show run in full screen?

When it starts, the browser page that it runs in is less than half of the screen and so most of the content is not visible and shows the browser task bar, obviously its easy to get the videos to play at the required size but nothing else.

Many thanks,
Pete

**Comment by KenT2** [comment]
-f command line option
Its in the manual under 'black box'

**Comment by Peter-Brown-1** [comment]
I knew I was being stupid, I remember reading it now!

Great program!

Thanks Ken,
Pete
