### ISSUE TITLE
omx controls or auto fade out to stop

### ISSUE THREAD

**Issue by ChrisLaurie** [KenT2/pipresents-gapless#5]
I am trying to use pipresents to play videos, images and text for our community theatre productions. It seems to do exactly what I want: play a specific video when needed, and pausing same.

Using the RadioButtonShow I am trying to get a controlled fade out to stop working. To try this I want to send a command to the omx player to reduce the brightness. Th idea being that I can send a few of these reduce brightness command and then when it is dim enough I can stop it.

However sending a command to omx player seems to have no effect. I map in the controls pp_key-- to omx-3 but the brightness does not reduce. If I run in debug mode I can see the keey is processed by pipresents- it says: "VideoPlayer: send control to omx: 3"

If I try the same with omx-STOP it also does not work - I can see the message about the control being sent but there is no action.

**Comment by ChrisLaurie** [comment]
Looks like I was confused and now I cannot find the web page that gave me the impression that keys 3 & 4 adjusts brightness. I also have subsequently been able to get the pause command to be passed through to omx and that it responds.

I am still looking for a method to get videos to fade to black and then I can stop them.

**Comment by KenT2** [comment]
You are correct that there is no brightness command, not even with dbus. You could edit the video offline to fade but I suspect with live theatre you want it to be interactive,

Alpha can be set in the omxplayer command. Looks like its been added for dynamic control here
https://github.com/popcornmix/omxplayer/issues/319  but could be dbus only

**Comment by ChrisLaurie** [comment]
I'm a bit out of my depth with Python, but is there a way for dbus control of omx player?

**Comment by KenT2** [comment]
No PP uses the keyboard interface. See you have asked for omxplayer to be extended which is good.
