### ISSUE TITLE
Radiobutton show carry on silently if media file not found

### ISSUE THREAD

**Issue by ChrisLaurie** [KenT2/pipresents-gapless#6]
I am trying to pre-configure a cue playing radiobuttonshow by loading it with files and mapping them to buttons 0-9 and a-z. The files are called cue01.mp4 and the link cue01 the next one is cue02 etc.

The actual files may or may not exist at runtime as I get the media files from the graphics guy and they are numbered this way. 

This way I can actually build the show and just swap out the files with a new set of files, when I am ready.

However currently if I accidentally hit a key for which the file does not exits, pipresents throws a message and then exits.

What I would like to happen is nothing - if the file does not exist, log an error in the terminal console, but don't fail, just replay the start track, which in my case is a black empty page.

**Comment by KenT2** [comment]
One way is to use short blank videos as dummy videos. I'm not sure the shortest you can use as omxplayer has been a bit finnicky with very short videos. I test with a 1 sec video, you may get shorter.

I don't think its right to modify PP for what you want but the audioplayer will forgives blank location fields, you could look at that and try modifying pp_videoplayyer.py in a similar fashion.

**Comment by ChrisLaurie** [comment]
I'm happy to try an do it as a custom change my side. I had a look at pp_videoplayer before my post and it seems that the methodology is quite wrapped around using the call_back procedure and that relies on loaded=OK & play and load-failed = fail to OS. Which I think is good.

I was hoping to amend radiobuttonshow by putting in a os.path.exists(track) test and if it fails do nothing or play the first track instead.

So far I have not been able to find the correct spot for that code.

**Comment by KenT2** [comment]
From a quick look I think after line 192 or 197 in do_play. Via track_ref and medialist you can get to the track location and see if it is blank.

**Comment by ChrisLaurie** [comment]
Not getting it right but in final show this would not be problem as all keyboard events will be computer generated.
