### ISSUE TITLE
Webeditor not opening files

### ISSUE THREAD

**Issue by hase5911** [KenT2/pipresents-gapless#63]
![open_profile_0](https://user-images.githubusercontent.com/6352063/31308567-18d3f736-ab79-11e7-9b18-cd773f7ab0e9.png)
![open_profile_1](https://user-images.githubusercontent.com/6352063/31308568-18f26798-ab79-11e7-8e4b-7d0ebfa9047e.png)
![open_profile_2](https://user-images.githubusercontent.com/6352063/31308569-18f436f4-ab79-11e7-9be2-5b4754bcca98.png)

Hi,
did a fresh install step by step following the instructions. Startetd example as described from the commandline. Everything OK. Started manager and accessed it trough the browser ... works ok from Raspi or from remote-Windows machine. Shows existing profiles, runs and stops shows ... everything ok. Starting editor with selected Show starts empty editor window. Open Profiles shows Profiles in a list, but selecting one pressing "OK" gives a "Nothing Selected" -Mesage. Tried everything, did a chmod 777 on all files. Not working. I'm able to create a new profile, this one is saved and can be run from the Manager. But, unable to load it afterwards. Very frustrating :-/.  Renamed old directories, installed Version 1.2.3 ... everything ok. Pure Python-Editor working ok. Any clues, what might disturb the Web-Editor or how i could find out?

Thanks an Regards

**Comment by KenT2** [comment]
The web editor is a bit unusual in the way it works. When you see the list of directories click on the name of the profile (pp_mediashow_1p3) not the directory icon, then press Open.

**Comment by hase5911** [comment]
Of course, you're right. Hope, my next question will be a a little bit more intelligent :-/.

Thanks for your great work an fast answering :-)
