### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by ChrisLaurie** [KenT2/pipresents-gapless#7]
Add to the message the ability to show the current date and current time. This would probably be through a macro (eg $date$ and $time$) with a formatting field for both.

Don't know python much, but I imagine a simple replace statement in the code that replaces the macro with the actual formatted data.

For time one would probably need a refresh from time to time. I can see this being used down to second level.

**Comment by KenT2** [comment]
You can do this already using the track_plugin API. There is an example in pp_plugin_1p3 and in pp_multiwindow_1p3 in the background show.
