### ISSUE TITLE
pp_timeofday_1p3 not working as intended.

### ISSUE THREAD

**Issue by Wilsas** [KenT2/pipresents-gapless#70]
Installed pipresents-gapless on rapberry pi 3 as per instructions in readme and tried running pp_timeofday_1p3. It started up ok, but it never shows "Show B" and pops this error: 

pi@Info-TV:~ $ python /home/pi/pipresents/pipresents.py -p pp_timeofday_1p3 -f -b
unclutter: someone created a sub-window to my sub-window! giving up
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1545, in __call__
    return self.func(*args)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 595, in callit
    func(*args)
  File "/home/pi/pipresents/pp_timeofday.py", line 151, in poll
    TimeOfDay.now = TimeOfDay.now + timedelta(seconds=1)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'datetime.timedelta'

**Comment by KenT2** [comment]
Hi
Thanks for reporting this. The fix is simple to implement.

In pp_timeofday.py  comment out line 31 by adding a hash to the first column- 
   TimeOfDay.now=None

I will fix it in the issued code  in the next version.

**Comment by KenT2** [comment]
Oh Dear, not so simple. The fix screws up shows started from the Start Show :-(

**Comment by KenT2** [comment]
Fixed in Version 1.3.4b

**Comment by shobikag24** [comment]
Hi Ken,

The timeofday profile is working fine but I cannot update it to the current time and my aim is to display my show every day starts at 10:00 AM and ends at 06:00 PM.

Help me out!

**Comment by KenT2** [comment]
Please be more specific. Is the Pi connected to the Internet

**Comment by shobikag24** [comment]
Yes, Pi is connected to the internet.

I'm running the pp_timeofday_1p3 profile. I've added two print statements in the pp_timeofday.py code [arount line 50 and line 65] to know did the time is updating or not. Actually, by code, the time and date are updating but when it comes to JSON file it is not getting updated. In JSON, whatever the values[date] of sim-day, sim-hour, sim-minute, sim-month, sim-second, sim-year are getting displayed and not the current time. So can you please tell me how to update this JSON.
Changed Code part,
    def init(self,pp_dir,pp_home,pp_profile,showlist,root,callback):
       
        # instantiate arguments
        TimeOfDay.root=root
        self.pp_dir=pp_dir
        self.pp_home=pp_home
        self.pp_profile=pp_profile
        self.showlist=showlist
        self.callback=callback

        # init variables
        self.testing=False
        self.tod_tick=500
        self.tick_timer=None
        # set time of day for if no schedule
        TimeOfDay.now = datetime.now().replace(microsecond=0)
        **print TimeOfDay.now**
        
        #  read and error check the schedule
        reason,message,schedule_enabled=self.read_schedule()
        if reason == 'error':
            return 'error',message,False
        
        if schedule_enabled is False:
            return 'normal','',False

        #create the initial events list
        if self.simulate_time is True:
            year= int(self.sim_year)
            month= int(self.sim_month)
            day = int(self.sim_day)
            **print day**
            hour= int(self.sim_hour)
            minute= int(self.sim_minute)
            second= int(self.sim_second)
            TimeOfDay.now = datetime(day = day, month =month, year=year,hour=hour, minute=minute, second=second)
            self.testing=True
            print '\nInitial SIMULATED time',TimeOfDay.now.ctime()
            self.mon.sched(self,TimeOfDay.now,'Testing is ON, Initial SIMULATED time ' + str(TimeOfDay.now.ctime()))
My JSON file,
{
 "issue": "1.3.5", 
 "shows": [
  {
   "admin-colour": "#ffffff", 
   "admin-font": "Helvetica 10 bold", 
   "admin-justify": "left", 
   "admin-x": "100", 
   "admin-y": "200", 
   "audio-speaker": "stereo", 
   "background-colour": "", 
   "background-image": "", 
   "child-track-ref": "", 
   "controls": "", 
   "disable-controls": "no", 
   "duration": "3", 
   "eggtimer-colour": "#ffffff", 
   "eggtimer-font": "Helvetica 10 bold", 
   "eggtimer-justify": "left", 
   "eggtimer-text": "Loading....", 
   "eggtimer-x": "100", 
   "eggtimer-y": "100", 
   "empty-track-ref": "", 
   "escape-track-ref": "", 
   "freeze-at-end": "yes", 
   "freeze-at-start": "no", 
   "hint-colour": "", 
   "hint-font": "", 
   "hint-justify": "left", 
   "hint-text": "", 
   "hint-x": "200", 
   "hint-y": "", 
   "image-rotate": "0", 
   "image-window": "original", 
   "interval": "0", 
   "medialist": "showa.json", 
   "mplayer-audio": "hdmi", 
   "mplayer-other-options": "", 
   "mplayer-volume": "0", 
   "omx-audio": "hdmi", 
   "omx-other-options": "", 
   "omx-volume": "0", 
   "omx-window": "original", 
   "pause-timeout": "", 
   "repeat": "repeat", 
   "sched-everyday": "day everyday\n10:00:00 open\n10:00:20 close\n10:00:40 open\n10:01:00 close", 
   "sched-monthday": "", 
   "sched-specialday": "", 
   "sched-weekday": "", 
   "sequence": "ordered", 
   "show-canvas": "", 
   "show-control-begin": "", 
   "show-control-end": "", 
   "show-ref": "showa", 
   "show-text": "Show A\n\nA repeating mediashow\nwhich runs at 10:00:00 until 10:00:20\n               and 10:00:40 until 10:01:00", 
   "show-text-colour": "#ffffff", 
   "show-text-font": "arial 30 bold", 
   "show-text-justify": "left", 
   "show-text-x": "100", 
   "show-text-y": "100", 
   "show-timeout": "0", 
   "title": "Show A", 
   "track-count-limit": "0", 
   "track-text-colour": "#ffffff", 
   "track-text-font": "Helvetica 20 bold", 
   "track-text-justify": "left", 
   "track-text-x": "0", 
   "track-text-y": "40", 
   "transition": "cut", 
   "trigger-end-param": "", 
   "trigger-end-type": "none", 
   "trigger-next-param": "", 
   "trigger-next-type": "continue", 
   "trigger-start-param": "", 
   "trigger-start-type": "start", 
   "trigger-wait-text": "Waiting for Trigger....", 
   "type": "mediashow", 
   "web-window": "warp"
  }, 
  {
   "admin-colour": "#ffffff", 
   "admin-font": "Helvetica 10 bold", 
   "admin-justify": "left", 
   "admin-x": "100", 
   "admin-y": "200", 
   "audio-speaker": "stereo", 
   "background-colour": "", 
   "background-image": "", 
   "child-track-ref": "", 
   "controls": "", 
   "disable-controls": "no", 
   "duration": "5", 
   "eggtimer-colour": "#ffffff", 
   "eggtimer-font": "Helvetica 10 bold", 
   "eggtimer-justify": "left", 
   "eggtimer-text": "Loading....", 
   "eggtimer-x": "100", 
   "eggtimer-y": "100", 
   "empty-track-ref": "", 
   "escape-track-ref": "", 
   "freeze-at-end": "yes", 
   "freeze-at-start": "no", 
   "hint-colour": "#ffffff", 
   "hint-font": "Helvetica 30 bold", 
   "hint-justify": "left", 
   "hint-text": "", 
   "hint-x": "200", 
   "hint-y": "100", 
   "image-rotate": "0", 
   "image-window": "original", 
   "interval": "0", 
   "medialist": "showb.json", 
   "mplayer-audio": "hdmi", 
   "mplayer-other-options": "", 
   "mplayer-volume": "0", 
   "omx-audio": "hdmi", 
   "omx-other-options": "", 
   "omx-volume": "0", 
   "omx-window": "original", 
   "pause-timeout": "", 
   "repeat": "repeat", 
   "sched-everyday": "day everyday\n10:00:20 open\n10:00:40 close", 
   "sched-monthday": "day 23 24\n10:01 open", 
   "sched-specialday": "day 2018-09-04", 
   "sched-weekday": "day friday saturday", 
   "sequence": "ordered", 
   "show-canvas": "", 
   "show-control-begin": "", 
   "show-control-end": "", 
   "show-ref": "showb", 
   "show-text": "", 
   "show-text-colour": "", 
   "show-text-font": "", 
   "show-text-justify": "left", 
   "show-text-x": "0", 
   "show-text-y": "0", 
   "show-timeout": "0", 
   "title": "Show B", 
   "track-count-limit": "0", 
   "track-text-colour": "#ffffff", 
   "track-text-font": "Helvetica 20 bold", 
   "track-text-justify": "left", 
   "track-text-x": "0", 
   "track-text-y": "40", 
   "transition": "cut", 
   "trigger-end-param": "", 
   "trigger-end-type": "none", 
   "trigger-next-param": "", 
   "trigger-next-type": "continue", 
   "trigger-start-param": "", 
   "trigger-start-type": "start", 
   "trigger-wait-text": "Waiting for Trigger....", 
   "type": "mediashow", 
   "web-window": "warp"
  }, 
  {
   "background-colour": "#000000", 
   "sched-enable": "yes", 
   "sched-everyday": "day everyday\n10:01:05 exitpipresents", 
   "sched-monthday": "", 
   "sched-specialday": "", 
   "sched-weekday": "", 
   "show-ref": "start", 
   "sim-day": "3", 
   "sim-hour": "9", 
   "sim-minute": "59", 
   "sim-month": "9", 
   "sim-second": "55", 
   "sim-year": "2018", 
   "simulate-time": "yes", 
   "start-show": "", 
   "start-show-ref": "start", 
   "title": "Start", 
   "type": "start"
  }
 ]
}

Respected Output for this profile,
pi@raspberrypi:~ $ python /home/pi/pipresents/pipresents.py -p pp_timeofday_1p3
2018-09-18 09:58:26
3

Initial SIMULATED time Mon Sep  3 09:59:55 2018
lines  5 everyday
Mon Sep  3 09:59:55 2018
lines  3 everyday
Mon Sep  3 09:59:55 2018
lines  1 weekday
Mon Sep  3 09:59:55 2018
lines  2 monthday
Mon Sep  3 09:59:55 2018
lines  1 specialday
Mon Sep  3 09:59:55 2018
lines  2 everyday
Mon Sep  3 09:59:55 2018

Schedule For Mon Sep  3 09:59:55 2018
Mon Sep  3 09:59:55 2018
  start
    exitpipresents:   10:01:05

  showa
    open:   10:00:00
    close:   10:00:20
    open:   10:00:40
    close:   10:01:00

  showb
    open:   10:00:20
    close:   10:00:40

Task list for today

start
exitpipresents 10:01:05

showa
close 10:01:00
open 10:00:40
close 10:00:20
open 10:00:00

showb
close 10:00:40
open 10:00:20

uncollectable garbage 0

**Comment by shobikag24** [comment]
Also I've included print statements in the code around line 405. The code is,
`def parse_day(self,lines,section,show_ref,show_type):
        # text
        # day monday
        # open 1:42
        # close 1:45
        # returns status,message,list of days,list of time lines
        print 'lines ',len(lines), section
        if section == 'everyday':
            status,message,days_list=self.parse_everyday(lines[0],show_ref)
            print TimeOfDay.now.ctime()
        elif section == 'weekday':
            status,message,days_list=self.parse_weekday(lines[0],show_ref)
            print TimeOfDay.now.ctime()
        elif section == 'monthday':
            # print 'parse_day',lines
            status,message,days_list=self.parse_monthday(lines[0],show_ref)
            print TimeOfDay.now.ctime()
        elif section == 'specialday':
            status,message,days_list=self.parse_specialday(lines[0],show_ref)
            print TimeOfDay.now.ctime()
        else:
            print TimeOfDay.now.ctime()
            return 'error','illegal section name '+section + ' '+ show_ref,[],[]
        if status == 'error':
            return 'error',message,[],[]`

**Comment by shobikag24** [comment]
Also, I've included print statements in the code around line 405.

The code is,

def parse_day(self,lines,section,show_ref,show_type):
        # text
        # day monday
        # open 1:42
        # close 1:45
        # returns status,message,list of days,list of time lines
        print 'lines ',len(lines), section
        if section == 'everyday':
            status,message,days_list=self.parse_everyday(lines[0],show_ref)
            print TimeOfDay.now.ctime()
        elif section == 'weekday':
            status,message,days_list=self.parse_weekday(lines[0],show_ref)
            print TimeOfDay.now.ctime()
        elif section == 'monthday':
            # print 'parse_day',lines
            status,message,days_list=self.parse_monthday(lines[0],show_ref)
            print TimeOfDay.now.ctime()
        elif section == 'specialday':
            status,message,days_list=self.parse_specialday(lines[0],show_ref)
            print TimeOfDay.now.ctime()
        else:
            print TimeOfDay.now.ctime()
            return 'error','illegal section name '+section + ' '+ show_ref,[],[]
        if status == 'error':
            return 'error',message,[],[]

**Comment by KenT2** [comment]
The .json file is not used any more all the data in the file is now in the profile. PP did not update the .json file anyway. See ReleaseNotes.txt

To make pp_timeofday_1p3 use real time change  Simulated Time to no in the start show.

**Comment by shobikag24** [comment]
Thanks for your quick reply.
