### ISSUE TITLE
web editor problem

### ISSUE THREAD

**Issue by Vorosh** [KenT2/pipresents-gapless#74]
Hey, Ken. I'm having a problem with the web editor. When I change a parameter, I see the following entry in the command line:

Traceback (most recent last call last):
   File "/home/pi/pipresents/remi/server.py", line 262, in on_message
     callback (** param_dict)
   File "/home/pi/pipresents/pp_web_edititem.py", line 228, in confirm_dialog
     self.field_content [field] = str (self.field_objs [field_index] .get_value ()). strip ()
UnicodeEncodeError: 'ascii' codec can not encode characters in position 0-6: ordinal not in range (128)

However, I can not save my changes. What are the problems and how to fix it?
Thank you!

**Comment by KenT2** [comment]
Th error message indicates you are typing a character which is not ASCII (ASCII = Latin  alphabet, 0-9 and some punctuation characters.)

Unfortunately PP does not support unicode
