### ISSUE TITLE
python-imaging-tk cannot be found anywhere

### ISSUE THREAD

**Issue by 54dchris** [KenT2/pipresents-gapless#78]
Cannot use python-imaging-tk in latest update of stretch. Says: 
Package python-imaging is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python-pil

but when i run pipresents i get:
from PIL import ImageTk
ImportError: cannot import name ImageTk

**Comment by KenT2** [comment]
looks like pil has been replaced by Pillow. I need to do some experiments as its not clear from Google what works. please try:

sudo apt-get install python-pil.imagetk

**Comment by 54dchris** [comment]
That worked thank you

**Comment by KenT2** [comment]
Something odd going on.

The commands in the readme work for me both before and after your query; they redirect the download to python-pil.imagetk
