### ISSUE TITLE
ChildChildMenu stops working + Bind sound to GPIO indput

### ISSUE THREAD

**Issue by martinschultzkristensen** [KenT2/pipresents-gapless#81]
When I make a profile like illustrated beneath I run into the error of childchild menu has no associated videos, though it has (I can run the Validate without errors)

Which brings me to the next question: 
I use the first  child mediashow to play a coinsound as entering the first menu. Can this be eliminated by binding a sound to a GPIO input? That would be awesome!

Best regards!

![pp_childmenu_issue](https://user-images.githubusercontent.com/27158803/41426465-ffc815b0-7003-11e8-8d15-54e7eb943c69.png)

**Comment by KenT2** [comment]
its odd that submenu1 and submenu2 are OK whereas submenu3 is not. Have your tracks in submenu3 got track references?
I am going to look into implementing the beep, it should not be too difficult except for the time delay for mplayer start up.
try running the menu from the Start show

**Comment by KenT2** [comment]
Beep on input event is now in [pipresents-beep]
Although this is in a new repository it is currently no more than a small upgrade to gapless
