### ISSUE TITLE
MediaList auto-restart

### ISSUE THREAD

**Issue by vsocrates** [KenT2/pipresents-gapless#82]
Hi Ken, 

My goal is to automatically check if the list of media in the `pp_home/media` directory has changed, and if so, to refresh the list from within the app. I started looking through the code, and it seems that I need to change either `pp_mediashow.py` or `pp_show.py`. Could you please point me in the right direction to make these code changes? Thanks!

**Comment by KenT2** [comment]
Hi
I don't think you need to change any code, just use a liveshow instead of a mediashow and put the tracks in the pp_live_tracks directory
