### ISSUE TITLE
Count number of Button clicks

### ISSUE THREAD

**Issue by HoneyBearUK** [KenT2/pipresents-gapless#92]
Hi Ken,
I have 10 shows running on my setup each started by a button press and it would be good to know their popularity.
Is their a way I can count the number of times a button was pressed to start a show and record to a text file?
I do not need to know each request time, just a total for the day.
Many thanks,
Stewart

**Comment by KenT2** [comment]
See Manual section 22.1  - Statistics Production. The other possibility is Counters

**Comment by HoneyBearUK** [comment]
Hi Ken,I've downloaded the latest version now and that looks good.Many thanks.Sent from Samsung tablet.
-------- Original message --------From: Ken <notifications@github.com> Date: 04/11/2018  20:19  (GMT+00:00) To: KenT2/pipresents-gapless <pipresents-gapless@noreply.github.com> Cc: HoneyBearUK <stew.wilbur@btinternet.com>, Author <author@noreply.github.com> Subject: Re: [KenT2/pipresents-gapless] Count number of Button clicks (#92) See Manual section 22.1  - Statistics Production. The other possibility is Counters

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/KenT2/pipresents-gapless","title":"KenT2/pipresents-gapless","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/KenT2/pipresents-gapless"}},"updates":{"snippets":[{"icon":"PERSON","message":"@KenT2 in #92: See Manual section 22.1  - Statistics Production. The other possibility is Counters"}],"action":{"name":"View Issue","url":"https://github.com/KenT2/pipresents-gapless/issues/92#issuecomment-435702236"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/KenT2/pipresents-gapless/issues/92#issuecomment-435702236",
"url": "https://github.com/KenT2/pipresents-gapless/issues/92#issuecomment-435702236",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [KenT2/pipresents-gapless] Count number of Button clicks (#92)",
"sections": [
{
"text": "",
"activityTitle": "**Ken**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@KenT2",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"KenT2/pipresents-gapless\",\n\"issueId\": 92,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"KenT2/pipresents-gapless\",\n\"issueId\": 92\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/KenT2/pipresents-gapless/issues/92#issuecomment-435702236"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 406180686\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by HoneyBearUK** [comment]
Ken, many thanks the in build Statistics are great.
